version: "3.8"
services:
  remnantguess:
    container_name: remnantguess
    image: remnantguess
    build: ./
    environment:
      - LOGLEVEL=20
    volumes:
      - ./main.py:/app/main.py
      - ./posteriors:/app/posteriors
      - ./results:/app/results
      - ./config:/app/config
      - ./utils:/app/utils
    command: python3 main.py

  remnantguess_jupyter:
    container_name: remnantguess_jupyter
    image: remnantguess
    ports:
      - ${port}:8888
    environment:
      - LOGLEVEL=20
    volumes:
      - ./notebook:/app
      - ./posteriors:/app/posteriors
      - ./results:/app/results
      - ./config:/app/config
      - ./utils:/app/utils
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    command: jupyter notebook
