version: "3.8"

x-env: &env
  - LOGLEVEL=${LOGLEVEL}
  - MAX_WORKER=${MAX_WORKER}
  - LOGFILEPATH=/home/${USERNAME}/src/results/log.txt

x-build: &build
  context: ./
  args:
    USERNAME: ${USERNAME}
    USER_ID: ${USER_ID}
    GROUP_ID: ${GROUP_ID}
    TZ: ${TZ}

x-posterior-dir: &posterior-dir ./src/posteriors:/home/${USERNAME}/src/posteriors

x-results-dir: &results-dir ./src/results:/home/${USERNAME}/src/results

x-configs-dir: &configs-dir ./src/configs:/home/${USERNAME}/src/configs

services:
  ancestral_bh:
    container_name: ancestral-bh
    image: ancestral-bh:${VERSION}
    build: *build
    environment: *env
    volumes:
      - *posterior-dir
      - *results-dir
      - *configs-dir
    command: python3 main.py

  ancestral_bh_jupyter:
    container_name: ancestral-bh-jupyter
    image: ancestral-bh:${VERSION}
    build: *build
    environment: *env
    volumes:
      - *posterior-dir
      - *results-dir
      - *configs-dir
    ports:
      - ${PORT}:8888
    command: jupyter lab --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''
