run_label: "general"
seed: 2023

prior:
  load_results: false
  mass_injection: false
  # Path to results.csv
  csv_path: "filepath"

posterior:
  mass_injection: false

  json_path:
    label: "filepath"

  h5_path:
    label: "filepath"
