# Number of black-hole mergers to simulate
num_binaries: 500000

binary_config:
  # fits: ['NRSur3dq8Remnant', 'NRSur7dq4Remnant', 'surfinBH7dq2']
  # NRSur3dq8Remnant: non precessing BHs with mass ratio<=8, anti-/aligned spin <= 0.8
  # NRSur7dq4Remnant: precessing BHs with mass ratio<=4, generic spin <= 0.8
  # surfinBH7dq2: precessing BHs with mass ratio <= 2, generic spin <= 0.8
  fits: "NRSur7dq4Remnant"

  # The option to simulate only mergers with aligned spin
  aligned_spin: false

  mass:
    # Domain settings (unit in solar mass)
    low: 5.
    high: 65.

    # The option to use Mahapatra mass distribution or not
    mahapatra: true

    # Provide a csv path if you have a customized mass distribution
    # The csv should contains "x": mass, "y": probability density
    csv_path:

  mass_ratio:
    # Domain settings (Dimensionless)
    low: 1.
    high: 6.

    # Provide a csv path if you have a customized mass ratio distribution
    # The csv should contains "x": mass_ratio, "y": probability density
    csv_path:

  spin:
    # Domain settings (Dimensionless)
    low: -0.8
    high: 0.8

  theta:
    # Domain settings (unit in pi)
    low: 0.
    high: 1.

  phi:
    # Domain settings (unit in pi)
    low: 0.
    high: 2.
