runlabel: "general"
seed: 2023

prior:
  loadResults: false
  # Path to results.csv
  pathToCSV: "filepath"

posterior:
  posteriorJson:
    label: "filepath"

  posteriorH5:
    label: "filepath"

estimation:
  kick:
    enable: true
    nbins: 200

  parental_mass:
    enable: true
    plotCorner: true
    sampleSize: 20 # Only useful for massInjection is disabled
    nbins: 200
    massInjection: false
