runlabel: "general"
seed: 2023

prior:
  loadResults: false
  # Path to results.csv
  pathToCSV: "filepath"

posterior:
  posteriorJson:
    label: "filepath"

  posteriorH5:
    label: "filepath"

estimation:
  enable: true
  plotCorner: true
  samplingSpinBinwidth: 0.05
  sampleSize: 10
  nbins: 200
