runlabel: "general"
seed: 2023

prior:
  loadResults: false
  # Path to results.csv
  pathToCSV: "filepath"

posterior:
  posteriorJson:
    label: "filepath"

  posteriorH5:
    label: "filepath"

estimation:
  kick:
    enable: true
  mass:
    enable: true
    massInjection: false
