amount: 500000
fits: "NRSur7dq4Remnant"

merger:
  align: false
  massInjection: false
  mass:
    min: 3.
    max: 150.
  massRatio:
    min: 1.
    max: 6.
  spin:
    min: -0.8
    max: 0.8
  theta:
    min: 0.
    max: 1. # in pi
  phi:
    min: 0.
    max: 2. # in pi
