[tool.poetry]
name = "archeo"
version = "1.0.0"
description = ""
authors = ["wyhwong <wyhwong@link.cuhk.edu.hk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.4"
numpy = "^1.26.3"
matplotlib = "^3.8.2"
seaborn = "^0.13.1"
# For surfinbh installation
surfinbh = "^1.2.3"
corner = "^2.2.2"
mpl-scatter-density = "^0.7"
tqdm = "^4.66.4"
# For pkg_resources, which is used by mpl-scatter-density
setuptools = "^70.3.0"
gwsurrogate = "^0.8"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
include_trailing_comma = true
lines_after_imports = 2

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
ipykernel = "^6.29.5"
pytest = "^8.3.3"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
